### ISSUE TITLE
purescript-affjax: Dynamic require

### ISSUE THREAD

**Issue by garyb** [Pauan/rollup-plugin-purs#5]
There will be several cases of this, as a pattern like this: https://github.com/slamdata/purescript-affjax/blob/071ca67b3535bd20e33b0765251c35a67278d77f/src/Network/HTTP/Affjax.js#L12 is used in a few libraries - whenever a module supports both node and browser and has a shim for one or the other, pretty much.

**Comment by Pauan** [comment]
The warning just means that it's using CommonJS in a dynamic way, which isn't allowed with ES6 modules.

In the specific case of `purescript-affjax`, it seems harmless. It's just doing a dynamic check for whether it's on Node.js or not, so that way it can load polyfills.

The problems happen when the code has imports/exports which aren't at the top level. As long as all the imports/exports are at the top level, then it's probably fine, and you can ignore the warnings.

**Comment by garyb** [comment]
We could probably use a comment or something for suppressing these warnings, as I know of at least 3 libraries that use this technique (affjax, debug, websockets-simple).

**Comment by Pauan** [comment]
I don't think the parser keeps the comments in the AST, though, so I don't think that would be a good solution. Perhaps something similar to `"use strict";`? Something like `"ignore warnings";`

**Comment by garyb** [comment]
Hmm, that's unfortunate - I wouldn't want to supress all warnings as it could hide other real issues.

**Comment by garyb** [comment]
`"ignore dynamic require"`; maybe? :wink:

**Comment by Pauan** [comment]
I think a comment would work if I used a regexp to parse the comments.

I think the form would be something like `// rollup-plugin-purs ignore dynamic require`, and similar for `module` and `exports`

**Comment by Pauan** [comment]
Okay, version 1.0.6 added in three comment pragmas:

```
// rollup-plugin-purs ignore dynamic exports
// rollup-plugin-purs ignore dynamic require
// rollup-plugin-purs ignore dynamic module
```

The comments must have that **exact** form, and they must appear at the top-level, without any spaces between the start of the line and the `//` part of the comment.

Each comment will disable a specific warning.
